### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by osiegmar** [nightwatchcybersecurity/rfc4180-bis#16]
Many CSV implementations have implemented a "skip empty lines" functionality when reading files. Empty lines are not permitted per this RFC. Maybe we should also add some textual representation about that. I thought that spread sheet tools may create empty lines if all cells of a row are empty. But MS Excel, Libre Office and Apple Numbers are correctly adding records with some comma.

**Comment by nightwatchcyber** [comment]
CSVW had this also under "skipBlankRows":
https://www.w3.org/ns/csvw

The current RFC allows empty lines, it says that same number of columns SHOULD be used, but is not required. The question is how widespread is this functionality.

This also leads to a larger question - how much functionality should be described within the RFC, and how much should be delegated to a metadata file like the one CSVW tried to define.

**Comment by osiegmar** [comment]
To ensure we're not talking cross-purposes, let's define:

**Empty record**
```
a,b,cCRLF
,,CRLF
d,e,fCRLF
```

**Empty/Blank line**
```
a,b,cCRLF
CRLF
d,e,fCRLF
```

Empty records are allowed by this RFC and are pretty common when using spreadsheet exports as a data source. Empty lines are not allowed by this RFC. I wouldn't say that empty lines are a widespread problem, just that almost every CSV implementation has implemented a way of handling this situation (read skipping those lines).

I don't think this RFC needs to (or should) be changed. But maybe an implementors note could help:

*Implementors should be aware of empty lines (lines that consists only of a linebreak) beside of multi-line fields. Those lines are invalid as per this RFC. Although lenient implementations typically just skip those lines.*

>This also leads to a larger question - how much functionality should be described within the RFC, and how much should be delegated to a metadata file like the one CSVW tried to define.

I highly doubt this metadata file will ever play a relevant role. Splitting up data in separate files is - from an implementors standpoint - a bit clumsy. Either one of both files could be missing, race conditions could happen (upload/download order) or "just" some other inconsistencies. I think if CSV is not enough for a specific job, other formats (XML, JSON, YAML) would be picked.

**Comment by nightwatchcyber** [comment]
As pr #17, this can be folded into a separate section to guide implementations.

**Comment by nightwatchcyber** [comment]
I added a section to the document for this, feel free to update as needed

**Comment by osiegmar** [comment]
I added a comment: https://github.com/nightwatchcybersecurity/rfc4180-bis/commit/e6b8e34b75d050dfa40b61e83c100ceff5d97c9b#r47002807
