### ISSUE TITLE
NULL representation

### ISSUE THREAD

**Issue by osiegmar** [nightwatchcybersecurity/rfc4180-bis#17]
Sometimes applications (like database imports/exports) needs to distinguish empty strings and NULL values in CSV data. I have seen different approaches for this:

* Use `a,,c` (the field between a and c is NULL) and `a,"",b` (the field between a and c is empty)
* Use `a,\N,c` (obvious)
* Use `"a","\N","c"` (obvious)

Or other string representations for NULL instead of `\N`.

See https://www.postgresql.org/docs/current/sql-copy.html for example.

> [...] Specifies the string that represents a null value. The default is \N (backslash-N) in text format, and an unquoted empty string in CSV format. You might prefer an empty string even in text format for cases where you don't want to distinguish nulls from empty strings.

Maybe we could address this issue in a reasonable way...

**Comment by nightwatchcyber** [comment]
We had something similar in CSWV, the value used was just "null":
https://www.w3.org/ns/csvw

With that being said, I am not sure how widespread this actually is. Does this ever occur outside of databases?

**Comment by osiegmar** [comment]
It occurs whenever CSV is used between machines or applications that have to deal with data where it is important to differentiate between "value (string) not known" and "value (string) is empty". As important it is for some databases (like PostgreSQL, MySQL and MSSQL but not Oracle) as important it could be for regular applications if this plays a role. It's is somewhat an edge case but searching the web for "CSV null" shows that it is a highly widespread edge case.

On the other hand it is about the semantics of the CSV and not about its syntax. The current grammar allows all the variants of this ticket. This RFC could probably never define a single way how NULL has to be handled. I was more thinking of a implementors reminder like:

*Implementors should be aware that some applications have to differentiate between empty and null values. Common practices of doing this are a) unquoted empty fields for **null** and quoted empty fields for **empty** or b) using a specific string like "null" to serialize actual **null** values. As it is part of the applications data interface this cannot be defined by this RFC.*

Of course this would need some some polishing before adding to the RFC as I'm obviously not a native speaker. :-)

**Comment by nightwatchcyber** [comment]
I am thinking about adding a separate section to guide implementations. This section would be advisory / informative, instead of normative. I think this would be a good candidate for that section.

**Comment by nightwatchcyber** [comment]
I added a section to the document for this, feel free to update as needed
