### ISSUE TITLE
Making UTF-8 default will break CSV files that contain binary data

### ISSUE THREAD

**Issue by Tux** [nightwatchcybersecurity/rfc4180-bis#24]
If a CSV file is a database dump or otherwise contains real binary data, setting the default to be UTF-8 will break those datasets.

I think it would be beteer to define that a CSV file can have a BOM, and optionally define which of the known BOM's is to be supported.

As Microsoft already has tools that export CSV files that have `sep=;` as *only* text on the first line, why not make that official and add other tags, like `sep=; encoding-utf-8 escape=\ skip-comment=1 ...`

FWIW my Text::CSV_XS already supports `sep=;` and tries hard to auto-detect UTF-8.
I implemented `comment_str` which supports any comment lead-in that does not start with SEP, QUO, ESC, or EOL.

**Comment by nightwatchcyber** [comment]
The default is already UTF-8 as per RFC6657, and updated by RFC7111 and seen in this IANA registration:
https://www.iana.org/assignments/media-types/text/csv

**Comment by osiegmar** [comment]
> If a CSV file is a database dump or otherwise contains real binary data, setting the default to be UTF-8 will break those datasets.

About the database dump and the character set:
The old version of this RFC specified US-ASCII as the default character set. This updated version only **extends** the valid characters by adding unicode (multibyte) characters. But of course, every application is free to choose a different character set – now and in the future.

About binary data:
As for all `text/*` mime types the purpose is text not binary. As CSV does neither allow control characters (ASCII codes 0x00-0x1F and 0x7F) nor extended ASCII codes (0x80-0xFF) I highly doubt that CSV really can be used for binary data.

> I think it would be beteer to define that a CSV file can have a BOM, and optionally define which of the known BOM's is to be supported.

Any unicode file could contain a BOM header. The BOM header is not specific to CSV by any means. The problem with BOM headers is that many applications does not support it (Java for example still has no built-in support for it). But you have a point here – we should add a few word about that to the section with *Common implementation concerns*.
For later reference: https://unicode.org/faq/utf_bom.html

> As Microsoft already has tools that export CSV files that have sep=; as only text on the first line, why not make that official and add other tags, like sep=; encoding-utf-8 escape=\ skip-comment=1 ...

I generally like the idea of having some sort of meta data header. But other than the character encoding, **this** would be a breaking change. It's a bummer that Microsoft didn't invest a bit more time and cleverness here – like reaching out the IETF with a proposal. A good idea also could have been using a special form of comment plus versioning (like `#csv-config: ver=1.0 sep=; escape="`)

First and foremost it's a question whether the RFC describes **common use** of CSV or tries to establish something new. Currently it's clearly about describing the common use.

**Comment by Tux** [comment]
Thanks for the answers.
I use CSV with real binary data on an almost daily basis, so I can confirm this is useful :)
What is way worse than real binary (no encoding, pure 8-bit) is *mixed* encodings.
And yes, I really have seen files that were a combination of cp1252, iso8859-1, and utf-8. Worse yet, I have seen files where fields inside a single record have different encodings. (Think Oracle with NVARCHAR fields with specific encoding). Oracle is not the best example of how CSV exports should be done.
For me, the only thing I do not yet support in my parser regarding this proposal is skipping empty lines. (and what if the line has just one (unquoted) space or just two quotes that would yield a valid record with just one empty field. If the option to skip whitespace around separators is active, how to distinguish between those?
My problem with "common use" is that I have the experience that there is no "common use". Too many generators never read the specs.
Keep up the good work. This is an interesting read

**Comment by osiegmar** [comment]
We probably all have seen files with mixed encodings when working with databases (and got nightmares about it :-)). But it is a bit like with HTML files – you could write files that are rendered properly by some browsers – even if they are broken. From my point of view it is pretty common to have **one** encoding per file and UTF-8 is very common nowadays. But applications sometimes have to deal with exceptions to those rules – as you pointed out.

About empty lines:

### Example 1)
```
a,b,cCRLF
CRLF
d,e,fCRLF
```
=> Line 2 is an empty line

### Example 2)
```
a,b,cCRLF
,,CRLF
d,e,fCRLF
```
=> Line 2 contains three empty fields (not an empty line)

### Example 3)
```
a,b,cCRLF
""CRLF
d,e,fCRLF
```
=> Line 2 contains one empty field (not an empty line)
**This example is against the recommendation of the spec – every record should contain the same number of fields.**

### Example 4)
```
a,b,cCRLF
 CRLF
d,e,fCRLF
```
=> Line 2 contains one field that is a space (not an empty line)
**This example is against the recommendation of the spec – every record should contain the same number of fields.**

**Comment by Tux** [comment]
I 100% agree, and will add an option to be able to skip empty lines (as opposed to returning a record with one empty field)

**Comment by Tux** [comment]
One more thing: if someone makes a database dump of a single column (or a complete (reference)table with just one field resulting in a single column), dropping empty lines will be invalid, as you will drop valid data rows.

**Comment by Tux** [comment]
`skip_empty_rows` now also added. I see a backward possible breakage if the parser does not specify the `EOL`. If the parser tries to auto-detect meta-stuff, like `sep`, `quo`, `esc`, and `eol`, and the data starts with two empty lines where the EOL is a single `CR`, I got conflicts.
Pondering if I should resolve that issue, as the problem does not exist if the EOL is explicitely set to `CR`

**Comment by osiegmar** [comment]
> One more thing: if someone makes a database dump of a single column (or a complete (reference)table with just one field resulting in a single column), dropping empty lines will be invalid, as you will drop valid data rows.

Good point. Tried to address this via https://github.com/nightwatchcybersecurity/rfc4180-bis/pull/26.

**Comment by osiegmar** [comment]
> `skip_empty_rows` now also added. I see a backward possible breakage if the parser does not specify the `EOL`. If the parser tries to auto-detect meta-stuff, like `sep`, `quo`, `esc`, and `eol`, and the data starts with two empty lines where the EOL is a single `CR`, I got conflicts.
> Pondering if I should resolve that issue, as the problem does not exist if the EOL is explicitely set to `CR`

I don't unterstand. Could you make an example how the file looks like?

```
CR
CR
abcCR
```

This?

**Comment by Tux** [comment]
Yes, that. If my parser is not explicitely told to use CR and skip_empty_rows is in effect, I see weird behavior. It is something for me to address, not for you.

**Comment by Tux** [comment]
Thanks for giving me loads of new tests :) All issues fixed. Will release https://github.com/Tux/Text-CSV_XS soon.

Do you think that implementing
```
my $csv = Text::CSV_XS->new ({ rfc4180bis => 1 }); # or { standard => "rfc4180bis" } or { rfc => "4180bis" }
```
as an alias to
```
my $csv = Text::CSV_XS->new ({
    strict          => 1,
    decode_utf8     => 1,
    skip_empty_rows => 1,
    comment_str     => "#",
    });
```
would make sense?

**Comment by Tux** [comment]
Text-CSV_XS-1.46.tgz released to CPAN
