### ISSUE TITLE
CSVW reference and text directionality

### ISSUE THREAD

**Issue by gkellogg** [nightwatchcybersecurity/rfc4180-bis#29]
The CSVW reference points to the working group page, which isn't really as useful as one of the specifications, itself. The best reference is probably to the "Model for Tabular Data and Metadata on the Web" at https://www.w3.org/TR/tabular-data-model/.

One issue called out in that document, which should be considered for RFC4180, is text direction. Specs such as HTML provide a means of specifying the text direction (RTL or LTR) of text fields. CSVW allows this to be described in metadata. There are also consideration on the directionality of columns within a table, as well. See [Bidirectional Tables](https://www.w3.org/TR/tabular-data-model/#bidirectional-tables).

**Comment by yakovsh** [comment]
Changing the reference to CSVW in draft -03 to the tabular data model one.

Regarding direction of text, I am not sure if it would be possible to do anything in CSV other then reference the right to left mark in Unicode. Going to check if other IETF standards do something similar.

**Comment by yakovsh** [comment]
Addressed in section 3.10
