### ISSUE TITLE
Comma within a column

### ISSUE THREAD

**Issue by ericthomas1** [nightwatchcybersecurity/rfc4180-bis#34]
Would be really nice to see an example of how to properly handle a comma _within_ a column.

If commas are not properly escaped within a column, it makes for a headache.

I believe item 6. of the spec covers this scenario, but the existing examples do not clearly show. 

Please consider adding the following examples or something similar:

`"key1: value1, key2: value2"`

Thank you

**Comment by yakovsh** [comment]
This was addressed in #35
