### ISSUE TITLE
Ambiguity of EOL sequence in quoted fields

### ISSUE THREAD

**Issue by osiegmar** [nightwatchcybersecurity/rfc4180-bis#36]
The section "Fields spanning multiple lines" of "Common implementation concerns" shows the following example:

```
"aaa","b CRLF<br/>
bb","c,c,c"CRLF<br/>
zzz,yyy,xxxCRLF
```

An important point to note is that the end-of-line sequence (CRLF) within the quoted field is part of the data, and not part of the CSV record's line break sequence as the data may be directly exported from a database for example. This has at least two consequences:

- The end-of-line sequence may be different from the CSV record's line break sequence.
- Implementers of CSV libraries should keep in mind that the exact sequence of end-of-line characters may be important to an application. Altering the end-of-line sequence may result in data corruption.

Since RFC-4180-bis specifies all binary data being valid in a CSV file, any altering of data might result in data corruption.

**Comment by yakovsh** [comment]
Added language addressing this in this commit: https://github.com/yakovsh/rfc4180-bis/commit/04b38b5ae6ede5c38c20813f689336b6dee679df
